services:
  - type: web
    name: talaextra-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: xvzs6TGf7xKo3qZIHSGXz0cRYeI4G37c2uGosSsFufueiVnQtnUcZ2IBXBfmS3WR
      - key: TALA_EXTRA_JWT_FALLBACK
        value: xvzs6TGf7xKo3qZIHSGXz0cRYeI4G37c2uGosSsFufueiVnQtnUcZ2IBXBfmS3WR
      - key: ALLOWED_ORIGINS
        value: https://talaextramkopo.vercel.app,https://www.talaextramkopo.vercel.app
      - key: FRONTEND_URL
        value: https://talaextramkopo.vercel.app
      - key: APP_PUBLIC_URL
        value: https://talaextraa.onrender.com
